# Generated by Django 6.0.3 on 2026-04-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_job_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('features', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='button_link',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='realtimehelp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='help/'),
        ),
        migrations.AlterField(
            model_name='whychoose',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='why/'),
        ),
    ]
