# Generated by Django 6.0.3 on 2026-04-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_job_support', '0002_demo_alter_hero_button_link_alter_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='title',
        ),
        migrations.AddField(
            model_name='demo',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='title_highlight',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demo',
            name='title_main',
            field=models.CharField(default='Get a Live', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demo',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
