# Generated by Django 6.0.3 on 2026-04-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_job_support', '0004_metatags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_title', models.CharField(blank=True, default='', max_length=255)),
                ('audience_description', models.TextField(blank=True, default='')),
                ('help_title', models.CharField(blank=True, default='', max_length=255)),
                ('process_title', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
