# Generated by Django 6.0.3 on 2026-04-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_job_support', '0005_sectioncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='help_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='process_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
