# Generated by Django 6.0.3 on 2026-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_job_support', '0007_remove_sectioncontent_help_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
