# Generated by Django 6.0.3 on 2026-04-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_job_support', '0008_alter_help_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='audience_eyebrow',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
