# Generated by Django 6.0.3 on 2026-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_metatags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacthero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/hero/'),
        ),
    ]
