# Generated by Django 6.0.3 on 2026-04-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('button_text', models.CharField(max_length=100)),
                ('background_color', models.CharField(default='#EAF0F8', max_length=7)),
                ('text_color', models.CharField(default='#1E3A68', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('submit_button_text', models.CharField(default='Submit Application', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('button_primary_text', models.CharField(default='Apply Now', max_length=100)),
                ('button_secondary_text', models.CharField(default='Learn More', max_length=100)),
                ('background_color', models.CharField(default='#EAF0F8', max_length=7)),
                ('text_color', models.CharField(default='#0C1A35', max_length=7)),
            ],
        ),
    ]
