# Generated by Django 6.0.3 on 2026-04-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, default="", max_length=255)),
                ("hero_subtitle", models.TextField(blank=True, default="")),
                ("hero_cta_text", models.CharField(blank=True, default="", max_length=255)),
                ("hero_cta_link", models.CharField(blank=True, default="", max_length=500)),
                ("why_title", models.CharField(blank=True, default="", max_length=255)),
                ("cta_title", models.CharField(blank=True, default="", max_length=255)),
                ("cta_subtitle", models.TextField(blank=True, default="")),
                ("faq_heading", models.CharField(blank=True, default="", max_length=255)),
                ("faq_intro", models.TextField(blank=True, default="")),
                ("faq_items", models.JSONField(blank=True, default=list)),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_content",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Page Content",
                "verbose_name_plural": "Category Page Contents",
            },
        ),
    ]

