# Generated by Django 6.0.3 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_categorypagecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorypagecontent",
            name="why_points",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="categorypagecontent",
            name="cta_buttons",
            field=models.JSONField(blank=True, default=list),
        ),
    ]

