# Generated by Django 6.0.3 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_categorypagecontent_buttons_and_why_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorypagecontent",
            name="seo_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="categorypagecontent",
            name="seo_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="categorypagecontent",
            name="seo_keywords",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated SEO keywords for the category page",
            ),
        ),
    ]

