# Generated by Django 6.0.3 on 2026-04-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField()),
                ('why_title', models.CharField(max_length=255)),
                ('why_points', models.TextField(help_text='Comma separated points')),
                ('blogs_heading', models.CharField(max_length=255)),
                ('cta_title', models.CharField(max_length=255)),
                ('cta_subtitle', models.TextField()),
                ('faq_heading', models.CharField(max_length=255)),
                ('faq_intro', models.TextField()),
            ],
        ),
    ]
