# Generated by Django 6.0.3 on 2026-04-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursespagecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursespagecontent',
            name='blogs_heading',
        ),
        migrations.AddField(
            model_name='coursespagecontent',
            name='faq_items',
            field=models.TextField(default='[]', help_text='JSON format: [{"question": "...", "answer": "..."}]'),
        ),
    ]
