# Generated by Django 6.0.3 on 2026-04-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_coursespagecontent_blogs_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursespagecontent',
            name='why_points',
            field=models.JSONField(default=list, help_text='List of points'),
        ),
    ]
