# Generated by Django 6.0.3 on 2026-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('features', 'Features section'), ('why_choose', 'Why choose section'), ('job_program', 'Job program section')], max_length=32, unique=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Section copy',
            },
        ),
        migrations.CreateModel(
            name='SupportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('plan_tabs', models.CharField(blank=True, help_text='Comma-separated labels for tabs, e.g. hourly, weekly, monthly', max_length=255)),
                ('cta_text', models.CharField(default='Get Started', max_length=80)),
                ('cta_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Support section',
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='highlights',
            field=models.TextField(blank=True, help_text='One highlight per line (shown with ✔). E.g. Upskill in SAP'),
        ),
        migrations.AddField(
            model_name='hero',
            name='popular_tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags under search.', max_length=500),
        ),
        migrations.AddField(
            model_name='hero',
            name='right_card_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='right_card_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hero',
            name='search_placeholder',
            field=models.CharField(blank=True, default='Search by skill', max_length=120),
        ),
        migrations.AlterField(
            model_name='hero',
            name='heading',
            field=models.TextField(help_text='Use two lines: line 1 plain, line 2 is shown in brand blue.'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
