# Generated by Django 6.0.3 on 2026-04-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_dynamic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportsection',
            name='cta_text',
            field=models.CharField(blank=True, default='Get Started', max_length=80),
        ),
    ]
