# Generated by Django 6.0.3 on 2026-04-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_support_cta_text_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncopy',
            name='section',
            field=models.CharField(choices=[('features', 'Features section'), ('why_choose', 'Why choose section'), ('job_program', 'Job program section'), ('faq', 'FAQ section')], max_length=32, unique=True),
        ),
    ]
