# Generated by Django 6.0.3 on 2026-04-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0002_course_remove_review_course_and_more'),
        ('courses', '0004_alter_coursespagecontent_why_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
