# Generated by Django 6.0.6 on 2026-07-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0006_skill_description_and_section_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesectionmeta',
            name='scrolling_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesectionmeta',
            name='scrolling_items',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coursesectionmeta',
            name='scrolling_location',
            field=models.CharField(choices=[('course', 'Course Details Page'), ('home', 'Home Page'), ('both', 'Both')], default='course', max_length=10),
        ),
    ]
