# Generated by Django 6.0.3 on 2026-04-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutHero",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(default="About Us", max_length=255)),
                ("paragraph_one", models.TextField(blank=True)),
                ("paragraph_two", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CtaSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True)),
                ("primary_button_text", models.CharField(default="Get Started", max_length=100)),
                ("primary_button_link", models.URLField(blank=True, null=True)),
                ("secondary_button_text", models.CharField(default="Contact Us", max_length=100)),
                ("secondary_button_link", models.URLField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "CTA section"},
        ),
        migrations.CreateModel(
            name="DemoSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(default="Get a Live Free demo", max_length=255)),
                ("features", models.JSONField(blank=True, default=list)),
                ("form_title", models.CharField(default="Book Your Free Demo", max_length=255)),
                ("form_subtitle", models.CharField(blank=True, max_length=255)),
                ("courses", models.JSONField(blank=True, default=list)),
                ("submit_button_text", models.CharField(default="Submit Your Details", max_length=100)),
            ],
            options={"verbose_name_plural": "Demo section"},
        ),
        migrations.CreateModel(
            name="ValueItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="ValuesSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(default="Our Values", max_length=255)),
                ("subtitle", models.TextField(blank=True)),
            ],
            options={"verbose_name_plural": "Values section"},
        ),
    ]
