# Generated by Django 6.0.3 on 2026-04-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_metatags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerServicesHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
