# Generated by Django 6.0.3 on 2026-04-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_training', '0002_hero_highlight_image_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empowersection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='corporate/empower/'),
        ),
    ]
