# Generated by Django 6.0.3 on 2026-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_training', '0004_metatags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage_title', models.CharField(blank=True, default='', max_length=255)),
                ('advantage_subtitle', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
