# Generated by Django 6.0.3 on 2026-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_training', '0005_sectioncontent_advantageitem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='process_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='process_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
