# Generated by Django 6.0.3 on 2026-04-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_training', '0006_processstep_icon_sectioncontent_process_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='demo_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='demo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='empower_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='empower_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='portfolio_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='portfolio_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
